// Generated by tools/ui_layout.py from ui/ui-info.csv. Do not edit by hand: change the CSV and run
// tools/build_assets.sh. Slots are centre + size in the 1954x1224 design space.
#pragma once

#include <juce_graphics/juce_graphics.h>

#include <iterator>

namespace pa::layout
{
inline constexpr float designWidth = 1954.0f;
inline constexpr float designHeight = 1224.0f;

struct Slot
{
    float cx, cy, w, h;

    juce::Rectangle<float> bounds() const { return { cx - w * 0.5f, cy - h * 0.5f, w, h }; }
};

inline constexpr Slot analyseButton     { 1737.0f, 1002.0f, 249.0f, 249.0f };
inline constexpr Slot delayButton       { 807.0f, 377.0f, 117.0f, 117.0f };
inline constexpr Slot phaseInvertButton { 977.0f, 377.0f, 117.0f, 117.0f };
inline constexpr Slot phaseButton       { 1145.0f, 377.0f, 117.0f, 117.0f };
inline constexpr Slot delayLed          { 807.0f, 270.0f, 99.0f, 99.0f };
inline constexpr Slot phaseInvertLed    { 977.0f, 270.0f, 99.0f, 99.0f };
inline constexpr Slot phaseLed          { 1145.0f, 270.0f, 99.0f, 99.0f };
inline constexpr Slot meterButton       { 1737.0f, 723.0f, 249.0f, 249.0f };
inline constexpr Slot baseImage         { 977.0f, 612.0f, 1954.0f, 1224.0f };
inline constexpr Slot delaySwitch       { 473.0f, 280.0f, 77.0f, 194.0f };
inline constexpr Slot phaseSwitch       { 1487.0f, 352.0f, 77.0f, 194.0f };
inline constexpr Slot delayDisplay      { 251.0f, 507.0f, 282.0f, 100.0f };
inline constexpr Slot phaseDisplay      { 1710.0f, 507.0f, 282.0f, 100.0f };
inline constexpr Slot meterDisplay      { 827.0f, 859.0f, 1480.0f, 555.0f };
inline constexpr Slot delayKnob         { 253.0f, 272.0f, 245.0f, 245.0f };
inline constexpr Slot phaseKnob         { 1710.0f, 272.0f, 245.0f, 245.0f };
inline constexpr Slot rangeButton       { 1487.0f, 205.0f, 77.0f, 77.0f };
inline constexpr Slot upperRangeLabel   { 1851.0f, 408.0f, 67.5f, 32.0f };

// Every embedded image, by its file name in ui/ (and assets/images/).
enum class Image
{
    analyseInOff,
    analyseInOn,
    analyseOutOff,
    analyseOutOn,
    buttonIn,
    buttonOut,
    ledOff,
    ledOn,
    meterInOff,
    meterInOn,
    meterOutOff,
    meterOutOn,
    pluginBase,
    toggleSwitchCentre,
    toggleSwitchDown,
    toggleSwitchUp,
    knobs,
    count
};

inline constexpr const char* imageFileNames[] = {
    "analyse-in-off.png",
    "analyse-in-on.png",
    "analyse-out-off.png",
    "analyse-out-on.png",
    "button-in.png",
    "button-out.png",
    "led-off.png",
    "led-on.png",
    "meter-in-off.png",
    "meter-in-on.png",
    "meter-out-off.png",
    "meter-out-on.png",
    "plugin-base.png",
    "toggle-switch-centre.png",
    "toggle-switch-down.png",
    "toggle-switch-up.png",
    "knobs.png",
};

static_assert (std::size (imageFileNames) == (size_t) Image::count);
} // namespace pa::layout
