#pragma once

// Generated by prototype/oversampling.py; don't edit by hand. Hi/Lo's oversampling halfbands (plan 2.3):
// each a length 4K - 1 FIR whose centre tap (2K - 1) is 0.5, other odd taps 0, and even taps listed here
// (h[0], h[2], ..., h[4K - 2]), float32, exactly symmetric.
// clang-format off
namespace pa::dsp::halfband_tables
{
inline constexpr float narrow44[30] = {
    0.0020680767f, -0.002016965f, 0.002967789f, -0.004193668f,
    0.005751329f, -0.0077105877f, 0.010173994f, -0.01329745f,
    0.017313983f, -0.022639988f, 0.030051976f, -0.04123401f,
    0.060577057f, -0.104228765f, 0.3176815f, 0.3176815f,
    -0.104228765f, 0.060577057f, -0.04123401f, 0.030051976f,
    -0.022639988f, 0.017313983f, -0.01329745f, 0.010173994f,
    -0.0077105877f, 0.005751329f, -0.004193668f, 0.002967789f,
    -0.002016965f, 0.0020680767f,
};
inline constexpr float narrow48[16] = {
    -0.0039300593f, 0.006581208f, -0.011849324f, 0.019888764f,
    -0.03240387f, 0.053732216f, -0.099893235f, 0.31619614f,
    0.31619614f, -0.099893235f, 0.053732216f, -0.03240387f,
    0.019888764f, -0.011849324f, 0.006581208f, -0.0039300593f,
};
inline constexpr float wide[6] = {
    0.013049206f, -0.06387151f, 0.30161294f, 0.30161294f,
    -0.06387151f, 0.013049206f,
};
} // namespace pa::dsp::halfband_tables
// clang-format on
