"""Writes src/dsp/FractionalKernelTables.h from the low-delay kernels reference/subsample.py designs.

    .venv/bin/python reference/subsample.py           # writes reference/kernels/kernels_<rate>.txt
    .venv/bin/python reference/fractional_tables.py   # writes src/dsp/FractionalKernelTables.h

One table per rate class, each designed for the lowest rate of its class (a set designed for a rate meets the spec at
every higher rate, not at lower ones): 44.1 kHz for rates below 48 kHz, 48 kHz below 88.2 kHz,
88.2 kHz below 176.4 kHz, 176.4 kHz from there up.
"""

import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "reference" / "kernels"
DEST = ROOT / "src" / "dsp" / "FractionalKernelTables.h"
CLASSES = [44100, 48000, 88200, 176400]


def load(rate):
    text = (SRC / f"kernels_{rate}.txt").read_text()
    m = re.search(r"lookahead H = (\d+), taps N = (\d+)", text)
    lookahead, taps = int(m.group(1)), int(m.group(2))
    rows = {}
    for line in text.splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split()
        rows[int(parts[0])] = np.array([float(v) for v in parts[1:]], dtype=np.float32)
    assert sorted(rows) == list(range(1, 10)) and all(len(r) == taps for r in rows.values())
    return lookahead, taps, rows


def main():
    out = ["#pragma once", "",
           "// Generated by reference/fractional_tables.py from reference/subsample.py; don't edit by hand.",
           "// Low-delay minimax fractional-delay kernels: for fractions 1 to 9 tenths, N taps, oldest sample first (as",
           "// FractionalKernels::reversed()); the kernel's newest sample is `lookahead` samples ahead of the tap. Within",
           "// 0.02 dB and 0.01 samples (phase delay) from 20 Hz to 20 kHz at the class's lowest rate and above.",
           "// clang-format off", "namespace pa::dsp::fractional_tables", "{",
           "struct Table", "{",
           "    double minRate; // the rate it was designed for: used from here up to the next table's",
           "    int lookahead, taps;", "    const float* kernels; // [fraction - 1][taps]", "};", ""]
    for rate in CLASSES:
        lookahead, taps, rows = load(rate)
        out.append(f"inline constexpr float kernels{rate}[9 * {taps}] = {{")
        for f in range(1, 10):
            vals = ", ".join(f"{float(v)!r}f" for v in rows[f])
            out.append(f"    {vals},")
        out.append("};")
        out.append("")
    out.append("inline constexpr Table tables[] = {")
    for rate in CLASSES:
        lookahead, taps, _ = load(rate)
        out.append(f"    {{{rate}.0, {lookahead}, {taps}, kernels{rate}}},")
    out += ["};", "} // namespace pa::dsp::fractional_tables", "// clang-format on", ""]
    DEST.write_text("\n".join(out))
    print(f"wrote {DEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
