#!/usr/bin/env python3
"""Reads ui/ui-info.csv and either writes src/ui/Layout.h or prints the asset size list.

    .venv/bin/python tools/ui_layout.py header   # regenerate src/ui/Layout.h
    .venv/bin/python tools/ui_layout.py assets   # "<file> <width> <height>" per image, for build_assets.sh

CSV conventions: x/y are image CENTRES in the 1954x1224 design space. A row
without x/y covers the whole design space (the base image). A row without w/h borrows the size of
another row of the same image (the delay knob uses the phase knob's 245x245).

Adding a control: add its CSV rows, run tools/build_assets.sh, and add one entry to the editor's control
table (src/PluginEditor.cpp). Slot names are the CSV component names in camelCase.
"""

import csv
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "ui" / "ui-info.csv"
HEADER_PATH = ROOT / "src" / "ui" / "Layout.h"

DESIGN_W, DESIGN_H = 1954, 1224
DEFAULT_SCALE = 0.4   # a new editor opens at 782x490 (80% of the 977x612 reference)
ASSET_SCALE = 2.5     # assets ship at 2.5x of the default size: exactly 1:1 with the design space


def camel(name: str) -> str:
    words = name.replace("-", " ").split()
    return words[0].lower() + "".join(w[:1].upper() + w[1:] for w in words[1:])


def num(text: str):
    text = (text or "").strip()
    return float(text) if text else None


def read_rows():
    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        return [{k.strip(): (v or "").strip() for k, v in row.items()} for row in csv.DictReader(f)]


def build():
    rows = read_rows()

    # Fill missing sizes from another row using the same image.
    size_by_file = {}
    for r in rows:
        if r["file"] and num(r["w"]) and num(r["h"]):
            size_by_file.setdefault(r["file"], (num(r["w"]), num(r["h"])))

    slots = OrderedDict()  # component -> (cx, cy, w, h)
    images = OrderedDict()  # file -> max slot (w, h)
    for r in rows:
        w, h = num(r["w"]), num(r["h"])
        if w is None or h is None:
            if r["file"] not in size_by_file:
                sys.exit(f"ui-info.csv: '{r['component']}' has no size and no other row of '{r['file']}' has one")
            w, h = size_by_file[r["file"]]
        cx, cy = num(r["x"]), num(r["y"])
        if cx is None or cy is None:
            cx, cy = DESIGN_W / 2, DESIGN_H / 2

        slot = (cx, cy, w, h)
        name = camel(r["component"])
        if name in slots and slots[name] != slot:
            sys.exit(f"ui-info.csv: rows for '{r['component']}' disagree on position or size")
        slots[name] = slot

        if r["file"]:
            pw, ph = images.get(r["file"], (0, 0))
            images[r["file"]] = (max(pw, w), max(ph, h))
    return slots, images


def asset_size(w, h):
    k = DEFAULT_SCALE * ASSET_SCALE
    return round(w * k), round(h * k)


def write_header(slots, images):
    def f(v):
        return f"{v:g}.0f" if float(v).is_integer() else f"{v:g}f"

    lines = [
        "// Generated by tools/ui_layout.py from ui/ui-info.csv. Do not edit by hand: change the CSV and run",
        "// tools/build_assets.sh. Slots are centre + size in the 1954x1224 design space.",
        "#pragma once",
        "",
        "#include <juce_graphics/juce_graphics.h>",
        "",
        "#include <iterator>",
        "",
        "namespace pa::layout",
        "{",
        f"inline constexpr float designWidth = {f(DESIGN_W)};",
        f"inline constexpr float designHeight = {f(DESIGN_H)};",
        "",
        "struct Slot",
        "{",
        "    float cx, cy, w, h;",
        "",
        "    juce::Rectangle<float> bounds() const { return { cx - w * 0.5f, cy - h * 0.5f, w, h }; }",
        "};",
        "",
    ]
    width = max(len(n) for n in slots)
    for name, (cx, cy, w, h) in slots.items():
        lines.append(f"inline constexpr Slot {name:<{width}} {{ {f(cx)}, {f(cy)}, {f(w)}, {f(h)} }};")
    lines += [
        "",
        "// Every embedded image, by its file name in ui/ (and assets/images/).",
        "enum class Image",
        "{",
    ]
    lines += [f"    {camel(name)}," for name in images]
    lines += [
        "    count",
        "};",
        "",
        "inline constexpr const char* imageFileNames[] = {",
    ]
    lines += [f'    "{name}.png",' for name in images]
    lines += [
        "};",
        "",
        "static_assert (std::size (imageFileNames) == (size_t) Image::count);",
        "} // namespace pa::layout",
        "",
    ]
    HEADER_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {HEADER_PATH.relative_to(ROOT)} ({len(slots)} slots, {len(images)} images)")


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in ("header", "assets"):
        sys.exit(__doc__)
    slots, images = build()
    if sys.argv[1] == "header":
        write_header(slots, images)
    else:
        for name, (w, h) in images.items():
            aw, ah = asset_size(w, h)
            print(f"{name}\t{aw}\t{ah}")


if __name__ == "__main__":
    main()
