"""A/B material for the Hi/Lo de-cramping (HANDOVER item 1, user listening): the same settings at 44.1 and 96 kHz,
zero-latency first-order sections (until 2026-10-06) against the oversampled ones, on the P3 drum loop and pink noise.

    .venv/bin/python prototype/decramp_ab.py      # needs prototype/out/p3/*_in.wav (PhaseAlignDspTests "[p3]")
                                                  # → prototype/out/decramp/ (WAVs, report.md)

An all-pass alone sounds almost the same whatever its top-octave phase; what the phase does is change how the track
sums with another mic. So each render is the processed signal summed 50/50 with the dry input (latency-compensated,
as a host does), the way the plugin is used, and the report gives that sum's level per band: (1 + H) / 2, which is
0 dB where the two agree and drops where the lag nears 180°. The renders use the golden-tested Python references
(HiLo, HiLoOversampled), which the C++ matches within 1e-6.

Historical (the de-cramping was approved 2026-10-06): after the RANGE redesign the settings below are read in the new
mapping, with an angle above 90 meaning the 180 range, so the modes' sections differ from the ones this was listened to.
"""

import math
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

from hilo import HiLo, HiLoOversampled, analog_lag, lag, lag_oversampled
from oversampling import plan, response

ROOT = Path(__file__).resolve().parent
P3 = ROOT / "out" / "p3"
OUT = ROOT / "out" / "decramp"
SETTINGS = [("hi", 5.0, "just past 0°: a corner far above 20 kHz, the worst case"),
            ("lo", 95.0, "just past 90° in Lo: section 2's corner far up"),
            ("hi", 60.0, "a typical setting")]
SOURCES = ["drums", "pink"]
RATES = [44100, 96000]
FREQS = [2000, 5000, 10000, 14000, 16000, 18000, 20000]


def source(name, fs):
    x, sr = sf.read(P3 / f"phase_sweeps_{name}_in.wav", dtype="float64")  # every scenario has the same input
    x = x[: int(4.0 * sr)].T
    if fs != sr:
        g = math.gcd(fs, sr)
        x = resample_poly(x, fs // g, sr // g, axis=-1)
    return x


def render(kind, mode, theta, x, fs):
    if kind == "old":
        return HiLo(fs, mode, theta, theta > 90).process(x), 0
    p = HiLoOversampled(fs, mode, theta, theta > 90)
    return p.process(x), p.latency


def summed_db(kind, mode, theta, fs, f):
    """Level of (dry + wet) / 2 at f, in dB."""
    f = np.asarray(f, dtype=float)
    if kind == "analog":
        phi, g = analog_lag(mode, theta, f, theta > 90), 1.0
    elif kind == "old":
        phi, g = lag(mode, theta, f, fs, theta > 90), 1.0
    else:
        phi, g = lag_oversampled(mode, theta, f, fs, theta > 90), response(fs, f)
    return 20 * np.log10(np.abs(1 + g * np.exp(-1j * np.radians(phi))) / 2)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    md = ["# Hi/Lo de-cramping: A/B", "", "Generated by `prototype/decramp_ab.py`.", "",
          "Each WAV is the source summed 50/50 with Hi/Lo's output at one setting (the dry delayed by the latency, as a "
          "host compensates it), as when aligning against a second mic: `<setting>_<source>_<rate>_<old|new>.wav`. "
          "*old* is the zero-latency first-order sections (until 2026-10-06), *new* the oversampled ones. The aim: "
          "*new* sounds the same at 44.1 and 96 kHz, and *old* at 96 kHz (close to analog) is what *new* now gives at "
          "44.1 too. The `dry_` files are the sources alone.", "",
          "## The sum's level by frequency (dB)", "",
          "0 dB: the processed track agrees with the dry one there; lower: they partly cancel. *analog* is the target "
          "(analog sections with the same lag at each reference frequency).", ""]
    for mode, theta, why in SETTINGS:
        md += [f"### {mode.capitalize()} {theta:g}° ({why})", "",
               "| | " + " | ".join(f"{f / 1000:g} kHz" for f in FREQS) + " |",
               "|---|" + "---|" * len(FREQS)]
        rows = [("analog", None)] + [(k, fs) for fs in RATES for k in ("old", "new")]
        for kind, fs in rows:
            label = "analog" if fs is None else f"{kind}, {fs / 1000:g} kHz"
            db = summed_db(kind, mode, theta, fs or 48000, FREQS)
            md.append(f"| {label} | " + " | ".join(f"{v:+.1f}" for v in db) + " |")
        md.append("")

    for name in SOURCES:
        for fs in RATES:
            x = source(name, fs)
            sf.write(OUT / f"dry_{name}_{fs // 1000}k.wav", x.T.astype(np.float32), fs, subtype="FLOAT")
            for mode, theta, _ in SETTINGS:
                for kind in ("old", "new"):
                    y, latency = render(kind, mode, theta, x, fs)
                    dry = np.zeros_like(x)
                    dry[:, latency:] = x[:, : x.shape[1] - latency]
                    mix = 0.5 * (dry + y)
                    tag = f"{mode}{theta:g}_{name}_{fs // 1000}k_{kind}"
                    sf.write(OUT / f"{tag}.wav", mix.T.astype(np.float32), fs, subtype="FLOAT")

    lat = ", ".join(f"{fs / 1000:g} kHz {plan(fs)[2]} samples ({plan(fs)[2] / fs * 1e3:.2f} ms)"
                    for fs in (44100, 48000, 88200, 96000, 192000))
    md += ["## Latency of the new Hi/Lo", "", lat + ".", ""]
    (OUT / "report.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
