"""High-frequency behaviour and knob travel (user questions, 2026-10-06).

    .venv/bin/python prototype/hf_check.py      # → prototype/out/hf/report.md

1. Hi/Lo magnitude: all-pass, so flat to Nyquist at any setting?
2. Hi/Lo phase against analog first-order all-passes with the same phase at each section's reference frequency: the
   bilinear transform maps an analog section onto the digital one exactly at that frequency but "cramps" its response
   towards Nyquist, where every digital section reaches 180 degrees. How far apart are they per band, and so how much
   does a given knob setting's top end depend on the sample rate?
3. Constant: the FIR Hilbert's level and angle up to Nyquist (exactly 90 degrees by construction; the level rolls off
   only at the very ends).
4. The delay's fractional kernels between 20 kHz and Nyquist (their spec stops at 20 kHz).
5. Knob travel: for each step of the phase knob, the largest phase change anywhere from 20 Hz to 20 kHz. A dead zone
   would show as steps that change nothing.
"""

import math
from pathlib import Path

import numpy as np

from hilo import k_pair, split
import oversampling
import subsample

OUT = Path(__file__).resolve().parent / "out" / "hf"
RATES = [44100, 48000, 88200, 96000, 192000]
BANDS = [(20, 5000), (5000, 10000), (10000, 16000), (16000, 20000), (20000, 22050)]
F1 = {"hi": 150.1, "lo": 75.1}
F2 = {"hi": 150.1, "lo": 20 * 75.1}


def digital_phase(mode, theta, fs, f):
    """Lag in degrees of the two digital sections: 2 atan(k tan(pi f / fs)) each."""
    k1, k2 = k_pair(mode, theta, fs)
    t = np.tan(np.pi * f / fs)
    return np.degrees(2 * np.arctan(k1 * t) + 2 * np.arctan(k2 * t))


def oversampled_phase(mode, theta, fs, f):
    """Hi/Lo as built since the de-cramping: the sections at the oversampled rate (the halfbands add only delay)."""
    return digital_phase(mode, theta, fs * oversampling.plan(fs)[0], f)


def analog_phase(mode, theta, f):
    """Analog first-order all-passes with each section's lag at its reference frequency equal to the digital one's:
    2 atan(tan(theta_i / 2) f / f_i)."""
    t1, t2 = split(mode, theta)
    return np.degrees(2 * np.arctan(np.tan(np.radians(t1) / 2) * f / F1[mode])
                      + 2 * np.arctan(np.tan(np.radians(t2) / 2) * f / F2[mode]))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    md = ["# High frequencies and knob travel", "", "Generated by `prototype/hf_check.py`.", ""]
    thetas = np.arange(0.0, 180.01, 0.25)

    # 1. Magnitude: evaluate the sections' frequency response directly (H = (-p + z^-1) / (1 - p z^-1)).
    md += ["## 1. Hi/Lo level", "",
           "Each section is H(z) = (−p + z⁻¹) / (1 − p z⁻¹), an exact all-pass for any real p, so the level is 0 dB at",
           "every frequency and setting. Checked numerically over every knob step, to 0.999 × Nyquist:", ""]
    worst = 0.0
    for fs in RATES:
        f = np.linspace(20, 0.999 * fs / 2, 4000)
        z1 = np.exp(-1j * 2 * np.pi * f / fs)
        for mode in ["hi", "lo"]:
            for theta in thetas[::8]:
                h = np.ones_like(z1)
                for k in k_pair(mode, theta, fs):
                    p = 1 - 2 / (1 + k)
                    h *= (-p + z1) / (1 - p * z1)
                worst = max(worst, np.abs(20 * np.log10(np.abs(h))).max())
    md += [f"- worst level error at any rate, mode and setting: {worst:.2e} dB (double rounding)", ""]

    # 2. Phase against the analog sections.
    def band_table(phase):
        rows = []
        for fs in RATES:
            for mode in ["hi", "lo"]:
                cells = []
                for lo_f, hi_f in BANDS:
                    if lo_f >= fs / 2:
                        cells.append("–")
                        continue
                    f = np.geomspace(lo_f, min(hi_f, 0.999 * fs / 2), 300)
                    d = max(np.abs(phase(mode, th, fs, f) - analog_phase(mode, th, f)).max() for th in thetas)
                    cells.append(f"{d:.1f}")
                rows.append(f"| {fs / 1000:g} kHz | {mode} | " + " | ".join(cells) + " |")
        return rows

    header = ["| rate | mode | " + " | ".join(f"{a / 1000:g}–{b / 1000:g} kHz" for a, b in BANDS) + " |",
              "|---|---|" + "---|" * len(BANDS)]
    md += ["## 2. Hi/Lo phase against analog sections (cramping)", "",
           "Worst |digital − analog| lag in degrees over the knob's travel (every 0.25°), per band. The knob angle is",
           "exact at each section's reference frequency at every rate (the readout).", "",
           "### Zero latency (first-order sections at the session rate, until 2026-10-06)", "",
           "The difference grows towards Nyquist, where a digital section always reaches 180°. It is largest just past",
           "0° and 90°, where a section's corner sits highest. It can't be fixed at zero latency: for any stable",
           "all-pass, tan(lag / 2) is a reactance function of tan(π f / fs), so by Foster's reactance theorem",
           "tan(lag / 2) / tan(π f / fs) never decreases, and the first-order section already has the least lag above",
           "its reference frequency of any all-pass with the same lag there.", ""] + header + band_table(digital_phase)
    md += ["", "### Oversampled (as built since 2026-10-06; `prototype/oversampling.py`)", "",
           "| rate | factor | latency | level 20 Hz–20 kHz |", "|---|---|---|---|"]
    for fs in RATES:
        M, _, L = oversampling.plan(fs)
        lvl = 20 * np.log10(oversampling.response(fs, np.geomspace(20, 20000, 400)))
        md.append(f"| {fs / 1000:g} kHz | {M}x | {L} samples ({L / fs * 1e3:.2f} ms) | "
                  f"{lvl.min():+.3f} to {lvl.max():+.3f} dB |")
    md += [""] + header + band_table(oversampled_phase)
    md.append("")
    # Typical settings rather than the worst: the median over the travel at 16-20 kHz.
    md += ["The same, as the median over the knob's travel (a typical setting rather than the worst), 16–20 kHz:", ""]
    for fs in [44100, 48000, 96000]:
        f = np.geomspace(16000, 20000, 50)
        for mode in ["hi", "lo"]:
            cells = []
            for name, phase in (("zero latency", digital_phase), ("oversampled", oversampled_phase)):
                d = [np.abs(phase(mode, th, fs, f) - analog_phase(mode, th, f)).max() for th in thetas]
                cells.append(f"{name} median {np.median(d):.1f}°, 90th percentile {np.percentile(d, 90):.1f}°")
            md.append(f"- {fs / 1000:g} kHz {mode}: " + "; ".join(cells))
    md += ["", "Between rates (the same knob setting at 44.1 and at 192 kHz), worst over the travel:", ""]
    for mode in ["hi", "lo"]:
        for name, phase in (("zero latency", digital_phase), ("oversampled", oversampled_phase)):
            rows = []
            for lo_f, hi_f in BANDS[:4]:
                f = np.geomspace(lo_f, hi_f, 300)
                d = max(np.abs(phase(mode, th, 44100, f) - phase(mode, th, 192000, f)).max() for th in thetas)
                rows.append(f"{lo_f / 1000:g}–{hi_f / 1000:g} kHz: {d:.1f}°")
            md.append(f"- {mode}, {name}: " + ", ".join(rows))
    md += ["", "Oversampled, also checked over every 0.05° of θ at each rate: the lag never decreases as θ rises (20 Hz",
           "to 20 kHz), and the readout frequency's lag is the knob angle (see part 5).", ""]
    for fs in RATES:
        f = np.geomspace(20, 20000, 600)
        for mode in ["hi", "lo"]:
            L = np.array([oversampled_phase(mode, th, fs, f) for th in np.arange(0, 180.001, 0.05)])
            step = np.diff(L, axis=0).min()
            assert step > -1e-9, (fs, mode, step)

    # 3. Constant: the Hilbert's level near the ends.
    from p2_constant import hilbert_fir, taps_at
    md += ["## 3. Constant", "",
           "The rotation is cos θ · x[n − L] + sin θ · Hilbert(x). The Hilbert's phase is exactly 90° at every frequency",
           "(type III FIR), so the only error is its level, which rolls off to zero at DC and at Nyquist. At 90° the output",
           "is the Hilbert alone; at other angles a level error δ turns into an angle error of about δ · sin θ cos θ.", "",
           "| rate | Hilbert level at 20 Hz | 20 kHz | 21 kHz | 22 kHz | Nyquist − 100 Hz |", "|---|---|---|---|---|---|"]
    for fs in RATES:
        h = hilbert_fir(taps_at(4097, fs))
        def level(f):
            w = 2 * np.pi * f / fs
            n = np.arange(len(h))
            return 20 * np.log10(np.abs(np.sum(h * np.exp(-1j * w * n))))
        cells = [f"{level(f):+.3f} dB" if f < fs / 2 else "–" for f in [20, 20000, 21000, 22000, fs / 2 - 100]]
        md.append(f"| {fs / 1000:g} kHz | " + " | ".join(cells) + " |")
    md.append("")

    # 4. Fractional delay kernels above 20 kHz.
    md += ["## 4. The delay's fractional kernels above 20 kHz", "",
           "Worst level over fractions 0.1 to 0.9 (whole-sample delays are exact at every frequency). The spec stops at",
           "20 kHz; above it a kernel rolls off towards Nyquist, worst at a fraction of 0.5:", "",
           "| rate | 20 kHz | 21 kHz | 22 kHz | 23 kHz |", "|---|---|---|---|---|"]
    kaiser = {44100: (48, 7.0), 48000: (24, 6.0), 96000: (8, 7.0), 192000: (8, 8.0)}
    for fs, (taps, beta) in kaiser.items():
        cells = []
        for fc in [20000, 21000, 22000, 23000]:
            if fc >= fs / 2:
                cells.append("–")
                continue
            worst_db = 0.0
            for tenth in range(1, 10):
                b, _, _ = subsample.windowed_sinc(tenth / 10, taps, beta)
                w = 2 * np.pi * fc / fs
                db = 20 * np.log10(np.abs(np.sum(b * np.exp(-1j * w * np.arange(len(b))))))
                worst_db = min(worst_db, db)
            cells.append(f"{worst_db:+.2f} dB")
        md.append(f"| {fs / 1000:g} kHz | " + " | ".join(cells) + " |")
    md.append("")

    # 5. Knob travel.
    md += ["## 5. Knob travel", "",
           "Oversampled Hi/Lo, as built. The phase knob's angle is θ = knob × range. For each 0.25° step of θ (0.28% of the 90° travel), the largest",
           "lag change anywhere from 20 Hz to 20 kHz; and the lag at the mode's reference frequency, which the readout",
           "shows. A dead zone would be steps that change nothing.", "",
           "| rate | mode | smallest change per 0.25° step (where) | largest | readout frequency's lag: worst error vs θ |",
           "|---|---|---|---|---|"]
    for fs in [44100, 48000, 96000, 192000]:
        f = np.geomspace(20, 20000, 600)
        for mode in ["hi", "lo"]:
            lags = np.array([oversampled_phase(mode, th, fs, f) for th in thetas])
            step = np.abs(np.diff(lags, axis=0)).max(axis=1)
            i = int(step.argmin())
            # The readout: Hi = lag at f1; Lo up to 90 = lag at f1, past 90 = 90 + section 2's lag at f2.
            err = 0.0
            fo = fs * oversampling.plan(fs)[0]
            for th in thetas:
                k1, k2 = k_pair(mode, th, fo)
                t1 = math.degrees(2 * math.atan(k1 * math.tan(math.pi * F1[mode] / fo)))
                t2 = math.degrees(2 * math.atan(k2 * math.tan(math.pi * F2[mode] / fo)))
                shown = (t1 + t2 if mode == "hi" else (t1 if th <= 90 else 90 + t2))
                err = max(err, abs(shown - th))
            md.append(f"| {fs / 1000:g} kHz | {mode} | {step[i]:.3f}° ({thetas[i]:.2f}–{thetas[i + 1]:.2f}°) | "
                      f"{step.max():.2f}° | {err:.4f}° |")
    md += ["", "Every step moves the phase somewhere in the audible band (no dead zone at either end), and the angle the",
           "readout shows is the knob's to within the error in the last column. Constant is a true rotation by θ at every",
           "frequency, so its travel is linear by construction.", ""]

    (OUT / "report.md").write_text("\n".join(md) + "\n")
    print((OUT / "report.md").read_text())


if __name__ == "__main__":
    main()
