"""P3 groundwork: the worst-case automation renders as WAVs, and where their worst sample steps are.

    build/PhaseAlignDspTests_artefacts/Release/PhaseAlignDspTests "[p3]"   # C++ chain → prototype/out/p3/raw/
    .venv/bin/python prototype/p3_report.py                                  # → prototype/out/p3/ (WAVs, report.md, plots)

The renders come from the real C++ chain (tests/dsp/P3Renders.cpp), with the plugin's own fade lengths and changes
applied at 64-sample callback boundaries, so the listening session tunes what will ship. This script only reads them.

For each render it finds the largest sample-to-sample steps (at least 20 ms apart), when they happen and which event
came just before, and compares them with the largest step in the input. A transition that is smooth enough adds little
to the signal's own steps; a click shows up as a step far above them. On the 100 Hz sine (0.5 peak) the signal's own
step is 0.0065, so anything much above that is the transition itself; the pink noise and drum loop are for listening.
"""

import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import soundfile as sf
from scipy.signal import butter, sosfiltfilt

OUT = Path(__file__).resolve().parent / "out" / "p3"
RAW = OUT / "raw"
FS = 48000
SOURCES = ["sine100", "pink", "drums"]
STEMS = ["kick", "snare", "bass", "guitar", "hats"]  # the user's pairs, when the render found them (captures/)
TOP = 5
APART_S = 0.02
SKIP_S = 0.05  # the sources fade in over 10 ms; the onset is not a transition


def audible(x):
    """Low-passed at 20 kHz (zero phase): a step that is only a burst near Nyquist disappears here."""
    return sosfiltfilt(butter(8, 20000, fs=FS, output="sos"), x, axis=0)


def load(path):
    x = np.fromfile(path, dtype=np.float32)
    return x.reshape(-1, 2)


def read_events(path):
    events = []
    for line in path.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        sample, latency, what = line.split("\t", 2)
        events.append((int(sample), int(latency), what))
    return events


def worst_steps(x, count=TOP, apart=int(APART_S * FS)):
    """The `count` largest |x[n] - x[n-1]| over both channels, at least `apart` samples from each other."""
    step = np.abs(np.diff(x, axis=0)).max(axis=1)
    step[: int(SKIP_S * FS)] = 0.0
    order = np.argsort(step)[::-1]
    picked = []
    for i in order:
        if all(abs(i - j) >= apart for j in picked):
            picked.append(int(i))
            if len(picked) == count:
                break
    return [(i + 1, float(step[i])) for i in picked]


def preceding(events, sample):
    before = [e for e in events if e[0] <= sample]
    return before[-1] if before else None


def describe(events, sample):
    e = preceding(events, sample)
    if e is None:
        return "-"
    # The output is later than the change by up to the latency, so say how long after it, in ms.
    return f"{e[2]} (+{1000 * (sample - e[0]) / FS:.1f} ms)"


def main():
    if not RAW.exists():
        raise SystemExit(f"no renders in {RAW}: run PhaseAlignDspTests \"[p3]\" first (Release build)")
    scenarios = sorted(p.name[: -len(".events.txt")] for p in RAW.glob("*.events.txt"))
    md = ["# P3: worst-case automation through the C++ chain", "",
          "Generated by `prototype/p3_report.py` from `tests/dsp/P3Renders.cpp` renders (48 kHz, 64-sample callbacks,",
          "the plugin's own fade lengths: 50 ms crossfades for delay changes, polarity and stage on/off; 10 + 10 ms",
          "around a latency change; 30 ms angle smoothing and Hi/Lo glides, 20 ms in Constant). Listen to the WAVs in",
          "this folder (`<scenario>_<source>_in.wav` / `_out.wav`, 32-bit float); `events/<scenario>.txt` lists every",
          "change with its time and the latency after it.", "",
          "**Worst step** is the largest sample-to-sample change in the output (either channel); **ratio** compares it",
          "with the input's largest. On the sine the input's own step is 0.0065: a smooth transition stays within a few",
          "times that, a hard switch would step by up to 1.0. **To 20 kHz** is the same after a 20 kHz low-pass (zero",
          "phase), so a burst that is only near Nyquist doesn't count. Times are in the output; a change is heard after",
          "the latency (up to 4.5 ms with the delay on, 43 ms more in Constant).", "",
          "| scenario | source | worst step | to 20 kHz | input's worst (to 20 kHz) | ratio (to 20 kHz) | at | just after |",
          "|---|---|---|---|---|---|---|---|"]
    listen = ["", "## Where to listen first", "",
              "The three largest steps of each render. On the sine they point at the transitions themselves; on the",
              "pink noise and drum loop the material's own transients are as large, so those times are only places to",
              "start listening (the event list has every change).", ""]
    (OUT / "events").mkdir(parents=True, exist_ok=True)
    for scenario in scenarios:
        events = read_events(RAW / f"{scenario}.events.txt")
        lines = ["time (s)\tlatency after (samples)\tevent"]
        lines += [f"{s / FS:.4f}\t{lat}\t{what}" for s, lat, what in events]
        (OUT / "events" / f"{scenario}.txt").write_text("\n".join(lines) + "\n")
        listen.append(f"- **{scenario}**")
        for source in SOURCES + [f"stem_{t}" for t in STEMS if (RAW / f"{scenario}_stem_{t}_in.f32").exists()]:
            x_in = load(RAW / f"{scenario}_{source}_in.f32")
            x_out = load(RAW / f"{scenario}_{source}_out.f32")
            sf.write(OUT / f"{scenario}_{source}_in.wav", x_in, FS, subtype="FLOAT")
            sf.write(OUT / f"{scenario}_{source}_out.wav", x_out, FS, subtype="FLOAT")
            steps = worst_steps(x_out)
            band = worst_steps(audible(x_out), count=1)[0][1]
            skip = int(SKIP_S * FS)
            in_band = float(np.abs(np.diff(audible(x_in)[skip:], axis=0)).max())
            at, value = steps[0]
            md.append(f"| {scenario} | {source} | {value:.4f} | {band:.4f} | {in_band:.4f} | {band / in_band:.2f} | "
                      f"{at / FS:.3f} s | {describe(events, at)} |")
            times = ", ".join(f"{s / FS:.3f} s ({v:.3f}, after {describe(events, s)})" for s, v in steps[:3])
            listen.append(f"  - {source}: {times}")
            if source == "sine100":
                plot(scenario, x_out, events, steps)
    md += listen
    md += ["", "## Plots", "",
           "For each scenario, the sine render with the events marked, and the three worst steps zoomed (±10 ms):", ""]
    md += [f"![{s}](plots/{s}.png)" for s in scenarios]
    (OUT / "report.md").write_text("\n".join(md) + "\n")
    print((OUT / "report.md").read_text())


def plot(scenario, y, events, steps):
    (OUT / "plots").mkdir(parents=True, exist_ok=True)
    t = np.arange(len(y)) / FS
    fig = plt.figure(figsize=(14, 7))
    top = fig.add_subplot(2, 1, 1)
    top.plot(t, y[:, 0], lw=0.4, color="tab:green")
    shown = [e for e in events if e[2] not in ("sweep", "fast sweep", "random")]
    for s, _, what in shown[:60]:
        top.axvline(s / FS, color="0.6", lw=0.5, ls=":")
    for s, v in steps[:3]:
        top.axvline(s / FS, color="tab:red", lw=0.8)
    top.set_title(f"{scenario}: 100 Hz sine out (left channel); events dotted, worst steps red")
    top.set_xlabel("time (s)")
    for k, (s, v) in enumerate(steps[:3]):
        ax = fig.add_subplot(2, 3, 4 + k)
        lo, hi = max(0, s - int(0.01 * FS)), min(len(y), s + int(0.01 * FS))
        ax.plot(1000 * t[lo:hi], y[lo:hi, 0], lw=0.8, label="L")
        ax.plot(1000 * t[lo:hi], y[lo:hi, 1], lw=0.8, label="R")
        ax.axvline(1000 * s / FS, color="tab:red", lw=0.6)
        e = preceding(events, s)
        ax.set_title(f"{s / FS:.3f} s: step {v:.4f}\nafter {e[2] if e else '-'}", fontsize=8)
        ax.set_xlabel("ms")
        ax.tick_params(labelsize=7)
    fig.tight_layout()
    fig.savefig(OUT / "plots" / f"{scenario}.png", dpi=90)
    plt.close(fig)


if __name__ == "__main__":
    main()
