"""A/B material for the RANGE / Hi-Lo redesign (user listening): the mapping as merged to master ("current") against the new
one ("new": each mode and range is its own shape, built from the reference unit's captured geometries and named as the
manual describes them; see prototype/hilo.py).

    .venv/bin/python prototype/range_ab.py <path to the old hilo.py>   # → prototype/out/range/ (WAVs, report.md)

Needs prototype/out/p3/*_in.wav (PhaseAlignDspTests "[p3]"). Each WAV is the source summed 50/50 with Hi/Lo's output
at one setting (the dry delayed by the latency, as a host compensates it), the way the plugin is used against a second
mic: `<MODE>_<range>_<knob>_<source>_<variant>.wav`. The report gives that sum's level by band, (1 + H) / 2 in dB: 0 dB
where the two agree, down where the lag nears 180 degrees. Both versions are the oversampled Hi/Lo (as built).
"""

import importlib.util
import math
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

import hilo as new
from oversampling import response

ROOT = Path(__file__).resolve().parent
P3 = ROOT / "out" / "p3"
OUT = ROOT / "out" / "range"
FS = 48000
SECONDS = 3.0
SOURCES = ["drums", "pink"]
KNOBS = [0.5, 1.0]
FREQS = [50, 100, 200, 500, 1000, 2000, 5000, 10000]


def load_old(path):
    spec = importlib.util.spec_from_file_location("hilo_old", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def source(name):
    x, sr = sf.read(P3 / f"phase_sweeps_{name}_in.wav", dtype="float64")
    x = x[: int(SECONDS * sr)].T
    if FS != sr:
        g = math.gcd(FS, sr)
        x = resample_poly(x, FS // g, sr // g, axis=-1)
    return x


def setting(old, variant, mode, wide, knob):
    """(processor, closed-form lag function f -> degrees) for one variant at one setting."""
    theta = knob * (180.0 if wide else 90.0)
    if variant == "current":
        proc = old.HiLoOversampled(FS, mode, theta)  # the old mapping reads the 0-180 angle directly
        from oversampling import plan
        return proc, (lambda f: old.lag(mode, theta, f, FS * plan(FS)[0]))
    proc = new.HiLoOversampled(FS, mode, theta, wide)
    return proc, (lambda f: new.lag_oversampled(mode, theta, f, FS, wide))


def main():
    old = load_old(sys.argv[1])
    OUT.mkdir(parents=True, exist_ok=True)
    md = ["# RANGE and Hi/Lo redesign: A/B", "", "Generated by `prototype/range_ab.py`.", "",
          "Variants: **current** (master: the knob's 0-90 is one section, past 90 a second one; HIGH = 150 Hz stacked, "
          "LOW = 75 Hz plus 1502 Hz) and **new** (RANGE out is one section: LOW at 75 Hz, HIGH at 150 Hz; RANGE in "
          "uses two sections over the whole travel: LOW = two stacked at 150 Hz, HIGH = 75 Hz plus 1502 Hz). Knob "
          "position 0.5 and 1.0 of the travel.", "",
          "The sum's level by frequency (dB), 0 = the processed and dry tracks agree:", ""]
    cases = [(m, w, k) for m in ("hi", "lo") for w in (False, True) for k in KNOBS]
    for mode, wide, knob in cases:
        md += [f"### {mode.upper()} range {'180' if wide else '90'}, knob {knob:g}", "",
               "| | " + " | ".join(f"{f:g}" for f in FREQS) + " |", "|---|" + "---|" * len(FREQS)]
        for variant in ("current", "new"):
            _, lagf = setting(old, variant, mode, wide, knob)
            f = np.asarray(FREQS, dtype=float)
            db = 20 * np.log10(np.abs(1 + response(FS, f) * np.exp(-1j * np.radians(lagf(f)))) / 2)
            md.append(f"| {variant} | " + " | ".join(f"{v:+.1f}" for v in db) + " |")
        md.append("")
    for name in SOURCES:
        x = source(name)
        sf.write(OUT / f"dry_{name}.wav", x.T.astype(np.float32), FS, subtype="FLOAT")
        for mode, wide, knob in cases:
            for variant in ("current", "new"):
                proc, _ = setting(old, variant, mode, wide, knob)
                y = proc.process(x)
                dry = np.zeros_like(x)
                dry[:, proc.latency:] = x[:, : x.shape[1] - proc.latency]
                tag = f"{mode.upper()}_{'180' if wide else '90'}_k{int(knob * 100)}_{name}_{variant}"
                sf.write(OUT / f"{tag}.wav", (0.5 * (dry + y)).T.astype(np.float32), FS, subtype="FLOAT")
    (OUT / "report.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
