"""Sub-sample delay: is it worth it, what resolution, and which interpolator (user question, 2026-10-06).

    .venv/bin/python prototype/subsample.py      # → prototype/out/subsample/ (report.md, interpolators.png)

Part 1, what the rounding costs: a whole-sample delay leaves up to half a sample of residual offset between the two
mics. Summing two equal, coherent signals offset by tau gives |cos(pi f tau)|, a high-frequency dip. A grid of g samples
leaves up to g/2.

Part 2, what a fractional delay costs: it needs an interpolator. Candidates, all evaluated at the worst fraction (0.5)
and at 0.1 / 0.25, from 20 Hz to 20 kHz at 44.1 and 48 kHz (the hard rates: least room above 20 kHz):
  - linear (2 taps): cheap, but a low-pass at fraction 0.5;
  - Lagrange 3rd order (4 taps);
  - Kaiser-windowed sinc (8 to 64 taps): linear phase, adds N/2 samples of latency, nearly flat if long enough;
  - Thiran all-pass (order 3): flat level by construction, delay error at the top, recursive (state makes moving it
    awkward).
"""

import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import freqz

OUT = Path(__file__).resolve().parent / "out" / "subsample"
RATES = [44100, 48000, 96000]
GRIDS = [1.0, 0.5, 0.1, 0.01]
CHECK_HZ = [5000, 10000, 16000, 20000]
FRACTIONS = [0.1, 0.25, 0.5]


# --- part 1 ------------------------------------------------------------------------------------------------------
def residual_dip_db(f, tau_samples, fs):
    return 20 * math.log10(abs(math.cos(math.pi * f * tau_samples / fs)))


# --- part 2: interpolators. Each returns (taps b, denominator a, nominal delay in samples) --------------------------
def linear(frac):
    return np.array([1 - frac, frac]), np.array([1.0]), frac


def lagrange3(frac):
    d = 1.0 + frac  # centred: delay between taps 1 and 2
    b = np.ones(4)
    for k in range(4):
        for m in range(4):
            if m != k:
                b[k] *= (d - m) / (k - m)
    return b, np.array([1.0]), d


def windowed_sinc(frac, taps, beta):
    """The kernel the plugin uses (src/dsp/FractionalDelay.h): a sinc centred at taps/2 - 1 + frac, under a Kaiser
    window of half-width taps/2 centred at the same point, normalised to unity at DC."""
    d = taps // 2 - 1 + frac
    x = np.arange(taps) - d
    w = np.i0(beta * np.sqrt(np.clip(1.0 - (x / (taps / 2)) ** 2, 0.0, None))) / np.i0(beta)
    b = np.sinc(x) * w
    return b / b.sum(), np.array([1.0]), d


def thiran(frac, order=3):
    d = order - 1 + frac + 0.5  # Thiran is accurate for d near the order
    a = np.ones(order + 1)
    for k in range(1, order + 1):
        prod = 1.0
        for i in range(order + 1):
            prod *= (d - order + i) / (d - order + k + i)
        a[k] = (-1) ** k * math.comb(order, k) * prod
    return a[::-1].copy(), a, d


def errors(b, a, nominal, fs, f_lo=20.0, f_hi=20000.0):
    f = np.geomspace(f_lo, f_hi, 800)
    w, h = freqz(b, a, worN=f, fs=fs)
    level = 20 * np.log10(np.abs(h))
    phase = np.unwrap(np.angle(h))
    delay = -phase / (2 * math.pi * f / fs)  # phase delay, in samples
    return f, level, delay - nominal


def windowed_sinc_beta(taps):
    return {8: 3.0, 16: 4.0, 32: 5.0, 48: 5.5, 64: 6.0}[taps]


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    md = ["# Sub-sample delay: worth it, resolution, interpolator", "",
          "Generated by `prototype/subsample.py`. Question from the user, 2026-10-06.", ""]

    md += ["## 1. What the rounding costs", "",
           "Two equal, coherent signals summed with the worst residual offset a grid leaves (half a step). The dip at",
           "each frequency, in dB (0 = perfect alignment):", "",
           "| rate | grid (samples) | worst residual | " + " | ".join(f"{f / 1000:g} kHz" for f in CHECK_HZ) + " |",
           "|---|---|---|" + "---|" * len(CHECK_HZ)]
    for fs in RATES:
        for g in GRIDS:
            tau = g / 2
            cells = " | ".join(f"{residual_dip_db(f, tau, fs):.2f}" for f in CHECK_HZ)
            md.append(f"| {fs / 1000:g} kHz | {g:g} | {tau:g} samples ({1e6 * tau / fs:.1f} µs, "
                      f"{34300 * tau / fs * 10:.2f} mm) | {cells} |")
    md += ["", "Real pairs are less coherent at the top than this (different mic positions, room), so these are upper",
           "bounds on the audible effect.", ""]

    # Part 2.
    candidates = [("linear (2 taps)", lambda fr: linear(fr), 0)]
    candidates.append(("Lagrange 3rd order (4 taps)", lambda fr: lagrange3(fr), 1))
    for taps in [8, 16, 32, 48, 64]:
        candidates.append((f"windowed sinc, {taps} taps", lambda fr, t=taps: windowed_sinc(fr, t, windowed_sinc_beta(t)),
                           taps // 2 - 1))
    candidates.append(("Thiran all-pass, order 3", lambda fr: thiran(fr), 3))

    md += ["## 2. Interpolators", "",
           "Worst level error (dB) and worst delay error (samples) from 20 Hz to 20 kHz, over fractions 0.1, 0.25 and",
           "0.5. Added latency is what has to be reported on top of the 4 ms: the samples the interpolator reads",
           "ahead of its tap.", "",
           "| interpolator | added latency | 44.1 kHz level | 44.1 kHz delay | 48 kHz level | 48 kHz delay | "
           "48 kHz to 18 kHz: level |",
           "|---|---|---|---|---|---|---|"]
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
    for name, make, ahead in candidates:
        cells = []
        for fs in [44100, 48000]:
            lev = dly = 0.0
            for fr in FRACTIONS:
                b, a, nominal = make(fr)
                f, level, derr = errors(b, a, nominal, fs)
                lev = max(lev, np.abs(level).max())
                dly = max(dly, np.abs(derr).max())
                if fs == 44100 and fr == 0.5:
                    axes[0].semilogx(f, level, label=name)
                    axes[1].semilogx(f, derr, label=name)
            cells += [f"{lev:.3f} dB", f"{dly:.3f}"]
        lev18 = 0.0
        for fr in FRACTIONS:
            b, a, nominal = make(fr)
            _, level, _ = errors(b, a, nominal, 48000, f_hi=18000.0)
            lev18 = max(lev18, np.abs(level).max())
        md.append(f"| {name} | {ahead} samples | " + " | ".join(cells) + f" | {lev18:.3f} dB |")
    axes[0].set_ylim(-3, 0.5)
    axes[0].set_ylabel("level (dB), fraction 0.5, 44.1 kHz")
    axes[1].set_ylim(-0.3, 0.3)
    axes[1].set_ylabel("delay error (samples)")
    for ax in axes:
        ax.set_xlim(20, 22050)
        ax.grid(True, which="both", alpha=0.3)
        ax.set_xlabel("frequency (Hz)")
    axes[0].legend(fontsize=7, loc="lower left")
    fig.suptitle("Fractional-delay interpolators at the worst fraction (0.5), 44.1 kHz")
    fig.tight_layout()
    fig.savefig(OUT / "interpolators.png", dpi=110)
    plt.close(fig)
    md += ["", "![interpolators](interpolators.png)", ""]

    # Part 3: the shortest windowed sinc per rate within 0.02 dB and 0.01 samples to 20 kHz (fractions 0.1 to 0.9).
    md += ["## 3. Shortest windowed sinc per rate", "",
           "Within 0.02 dB and 0.01 samples from 20 Hz to 20 kHz at every fraction 0.1 to 0.9, searching taps in steps",
           "of 8 and β from 3 to 8. Its latency is taps/2 − 1 samples.", "",
           "| rate | taps | β | worst level | worst delay | latency |", "|---|---|---|---|---|---|"]
    for fs in [44100, 48000, 88200, 96000, 176400, 192000]:
        found = None
        for taps in range(8, 129, 8):
            for beta in np.arange(3.0, 8.01, 0.5):
                lev = dly = 0.0
                for fr in np.arange(0.1, 0.95, 0.1):
                    b, a, nominal = windowed_sinc(fr, taps, beta)
                    _, level, derr = errors(b, a, nominal, fs)
                    lev, dly = max(lev, np.abs(level).max()), max(dly, np.abs(derr).max())
                if lev <= 0.02 and dly <= 0.01 and (found is None or lev + 10 * dly < found[2] + 10 * found[3]):
                    found = (taps, beta, lev, dly)
            if found is not None:
                break
        taps, beta, lev, dly = found
        md.append(f"| {fs / 1000:g} kHz | {taps} | {beta:g} | {lev:.4f} dB | {dly:.4f} | {taps // 2 - 1} samples "
                  f"({1000 * (taps // 2 - 1) / fs:.2f} ms) |")
    md.append("")

    (OUT / "report.md").write_text("\n".join(md) + "\n")
    print((OUT / "report.md").read_text())


if __name__ == "__main__":
    main()
